FROM node:20-slim AS builder

WORKDIR /build

COPY package*.json ./
RUN npm install

COPY . .
RUN node ./node_modules/vite/bin/vite.js build

FROM nginx:alpine

COPY --from=builder /build/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
